version: '3'
services:
  postgres:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data 
    networks:
      - local-network
networks: 
  local-network:
    driver: bridge
